#!/usr/bin/env node

var args = process.argv.slice(2);

if(args[0].match(/help/g) || args.length < 2){
    console.log(`Usage: ./append_output [--help] result output1 [ output2 ]

result: The JSON result of 1 test case.
output: The text to be appended to the output field of the result. Multiple outputs can be appended

`);

}

let res = {};

try {
  res = JSON.parse(args[0]);
} catch (e) {
  console.error('Cannot load result to append output');
  process.exit();
}

if(!('output' in res)){
  res.output = '';
}

// Append outputs
for (let i=1; i<args.length; i++) {
    res.output += args[i];
} 

console.log(JSON.stringify(res,null,2));